### ISSUE TITLE
CAMERA_MODEL_M5STACK_WIDE

### ISSUE THREAD

**Issue by Any-Winter-4079** [RuiSantosdotme/ESP32-CAM-Arduino-IDE#8]
Hey guys. For anyone using this amazing repo, if you have CAMERA_MODEL_M5STACK_WIDE, the needed pins are:

  #define PWDN_GPIO_NUM     -1
  #define RESET_GPIO_NUM    15
  #define XCLK_GPIO_NUM     27
  #define SIOD_GPIO_NUM     22
  #define SIOC_GPIO_NUM     23

  #define Y9_GPIO_NUM       19
  #define Y8_GPIO_NUM       36
  #define Y7_GPIO_NUM       18
  #define Y6_GPIO_NUM       39
  #define Y5_GPIO_NUM        5
  #define Y4_GPIO_NUM       34
  #define Y3_GPIO_NUM       35
  #define Y2_GPIO_NUM       32
  #define VSYNC_GPIO_NUM    25
  #define HREF_GPIO_NUM     26
  #define PCLK_GPIO_NUM     21

Fixes:

> camera: camera probe failed with error 0x105(esp_err_not_found)).

Hope this saves you some time!

**Comment by RuiSantosdotme** [comment]
Thank you! I just accepted the change:
https://github.com/RuiSantosdotme/ESP32-CAM-Arduino-IDE/blob/master/ESP32-CAM-Video-Streaming/ESP32-CAM-Access-Point-AP-Video-Streaming.ino
